# see: https://golangci-lint.run/usage/configuration/
version: "2"

run:
  go: "1.24"

linters:
  default: "all"
  disable:
    - "depguard"
    - "varnamelen"
  settings:
    cyclop:
      max-complexity: 20
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
    gocognit:
      min-complexity: 20
    gocyclo:
      min-complexity: 20
    godox:
      keywords:
        - "TODO"
        - "FIXME"
    lll:
      line-length: 100
      tab-width: 4
    makezero:
      always: true
    misspell:
      locale: "US"
      ignore-rules:
        - "some_word"
    nestif:
      min-complexity: 4
    testpackage:
      skip-regexp: "_inner_test.go"
  exclusions:
    generated: "lax"
    presets:
      - "comments"
      - "common-false-positives"
      - "legacy"
      - "std-error-handling"
    rules:
      - linters:
          - "dupl"
          - "errcheck"
          - "funlen"
          - "maintidx"
        path: "_test.go"
    paths:
      - ".github"
      - ".vscode"
      - "third_party$"
      - "builtin$"
      - "examples$"

formatters:
  enable:
    - "gci"
    - "gofmt"
    - "gofumpt"
    - "goimports"
  exclusions:
    generated: "lax"
    paths:
      - ".github"
      - ".vscode"
      - "third_party$"
      - "builtin$"
      - "examples$"
