# see: https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  go: "1.22"

output:
  sort-results: true

linters-settings:
  cyclop:
    max-complexity: 20
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
  gocognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 20
  godox:
    keywords:
      - "TODO"
      - "FIXME"
  lll:
    line-length: 100
    tab-width: 4
  makezero:
    always: true
  misspell:
    locale: "US"
    ignore-words:
      - "some_word"
  nestif:
    min-complexity: 4
  testpackage:
    skip-regexp: "_inner_test.go"

linters:
  disable:
    - "depguard"
    - "varnamelen"
    # ---- deprecated ---- #
    - "execinquery"
    - "gomnd"
    - "rowserrcheck"
    - "sqlclosecheck"
    - "wastedassign"
    # -------------------- #
  enable-all: true
  fast: false

issues:
  exclude-dirs:
    - ".github"
    - ".vscode"
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: "_test.go"
      linters:
        - "dupl"
        - "errcheck"
        - "funlen"
        - "maintidx"
